env:
 - CABALVER=1.22 GHCVER=7.10.2

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update

 - cabal sandbox init
 - cabal sandbox add-source Magic
 - cabal sandbox add-source Magic-Cards
 - cabal sandbox add-source Magic-CLI
 - cabal sandbox add-source Magic-Web-Server
 - cabal install --only-dependencies --enable-tests --enable-benchmarks Magic Magic-Cards Magic-CLI Magic-Web-Server

# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal install --enable-tests --enable-benchmarks Magic Magic-Cards Magic-CLI Magic-Web-Server
